// Generated by gencpp from file tracker/GazeEuler.msg
// DO NOT EDIT!


#ifndef TRACKER_MESSAGE_GAZEEULER_H
#define TRACKER_MESSAGE_GAZEEULER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tracker
{
template <class ContainerAllocator>
struct GazeEuler_
{
  typedef GazeEuler_<ContainerAllocator> Type;

  GazeEuler_()
    : yaw(0.0)  {
    }
  GazeEuler_(const ContainerAllocator& _alloc)
    : yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::tracker::GazeEuler_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tracker::GazeEuler_<ContainerAllocator> const> ConstPtr;

}; // struct GazeEuler_

typedef ::tracker::GazeEuler_<std::allocator<void> > GazeEuler;

typedef boost::shared_ptr< ::tracker::GazeEuler > GazeEulerPtr;
typedef boost::shared_ptr< ::tracker::GazeEuler const> GazeEulerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tracker::GazeEuler_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tracker::GazeEuler_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tracker::GazeEuler_<ContainerAllocator1> & lhs, const ::tracker::GazeEuler_<ContainerAllocator2> & rhs)
{
  return lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tracker::GazeEuler_<ContainerAllocator1> & lhs, const ::tracker::GazeEuler_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tracker

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tracker::GazeEuler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracker::GazeEuler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracker::GazeEuler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracker::GazeEuler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracker::GazeEuler_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracker::GazeEuler_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tracker::GazeEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08cb8274b6ddb17af5a842bca0b17db1";
  }

  static const char* value(const ::tracker::GazeEuler_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08cb8274b6ddb17aULL;
  static const uint64_t static_value2 = 0xf5a842bca0b17db1ULL;
};

template<class ContainerAllocator>
struct DataType< ::tracker::GazeEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tracker/GazeEuler";
  }

  static const char* value(const ::tracker::GazeEuler_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tracker::GazeEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 yaw\n"
;
  }

  static const char* value(const ::tracker::GazeEuler_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tracker::GazeEuler_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GazeEuler_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tracker::GazeEuler_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tracker::GazeEuler_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACKER_MESSAGE_GAZEEULER_H
