apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: x1-community
      app.kubernetes.io/instance: x1-community
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: x1-community
        app.kubernetes.io/instance: x1-community
        app.kubernetes.io/component: frontend
    spec:
      nodeSelector:
        dedicated: app
      imagePullSecrets:
        - name: basicai-registry
      containers:
        - name: frontend
          image: $FRONTEND_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 1
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app.kubernetes.io/name: x1-community
    app.kubernetes.io/instance: x1-community
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /main/$1
  name: frontend-main
spec:
  ingressClassName: nginx
  rules:
    - host: xtreme1.alidev.beisai.com
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /(.*)
            pathType: Prefix
  tls:
    - hosts:
        - xtreme1.alidev.beisai.com
      secretName: alidev.beisai.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /image-tool/$2
  name: frontend-image-tool
spec:
  ingressClassName: nginx
  rules:
    - host: xtreme1.alidev.beisai.com
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /tool/image(/|$)(.*)
            pathType: Prefix
  tls:
    - hosts:
        - xtreme1.alidev.beisai.com
      secretName: alidev.beisai.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /pc-tool/$2
  name: frontend-pc-tool
spec:
  ingressClassName: nginx
  rules:
    - host: xtreme1.alidev.beisai.com
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /tool/pc(/|$)(.*)
            pathType: Prefix
  tls:
    - hosts:
        - xtreme1.alidev.beisai.com
      secretName: alidev.beisai.com
