# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tracker/DL_Tracker.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DL_Tracker(genpy.Message):
  _md5sum = "4bd6d1a09d9f8eca2b38fa4b213ef574"
  _type = "tracker/DL_Tracker"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 yaw_head
float64 yaw_eye
uint32 label
"""
  __slots__ = ['yaw_head','yaw_eye','label']
  _slot_types = ['float64','float64','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       yaw_head,yaw_eye,label

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DL_Tracker, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.yaw_head is None:
        self.yaw_head = 0.
      if self.yaw_eye is None:
        self.yaw_eye = 0.
      if self.label is None:
        self.label = 0
    else:
      self.yaw_head = 0.
      self.yaw_eye = 0.
      self.label = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2dI().pack(_x.yaw_head, _x.yaw_eye, _x.label))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.yaw_head, _x.yaw_eye, _x.label,) = _get_struct_2dI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2dI().pack(_x.yaw_head, _x.yaw_eye, _x.label))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.yaw_head, _x.yaw_eye, _x.label,) = _get_struct_2dI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2dI = None
def _get_struct_2dI():
    global _struct_2dI
    if _struct_2dI is None:
        _struct_2dI = struct.Struct("<2dI")
    return _struct_2dI
