# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tracker/gazepoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class gazepoint(genpy.Message):
  _md5sum = "1e16063650569646887d2bce97f3d513"
  _type = "tracker/gazepoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point gaze_point_3d
geometry_msgs/Point norm_pos
float64 calib_rotation
uint32 label

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['gaze_point_3d','norm_pos','calib_rotation','label']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point','float64','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gaze_point_3d,norm_pos,calib_rotation,label

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gazepoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.gaze_point_3d is None:
        self.gaze_point_3d = geometry_msgs.msg.Point()
      if self.norm_pos is None:
        self.norm_pos = geometry_msgs.msg.Point()
      if self.calib_rotation is None:
        self.calib_rotation = 0.
      if self.label is None:
        self.label = 0
    else:
      self.gaze_point_3d = geometry_msgs.msg.Point()
      self.norm_pos = geometry_msgs.msg.Point()
      self.calib_rotation = 0.
      self.label = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7dI().pack(_x.gaze_point_3d.x, _x.gaze_point_3d.y, _x.gaze_point_3d.z, _x.norm_pos.x, _x.norm_pos.y, _x.norm_pos.z, _x.calib_rotation, _x.label))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.gaze_point_3d is None:
        self.gaze_point_3d = geometry_msgs.msg.Point()
      if self.norm_pos is None:
        self.norm_pos = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.gaze_point_3d.x, _x.gaze_point_3d.y, _x.gaze_point_3d.z, _x.norm_pos.x, _x.norm_pos.y, _x.norm_pos.z, _x.calib_rotation, _x.label,) = _get_struct_7dI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7dI().pack(_x.gaze_point_3d.x, _x.gaze_point_3d.y, _x.gaze_point_3d.z, _x.norm_pos.x, _x.norm_pos.y, _x.norm_pos.z, _x.calib_rotation, _x.label))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.gaze_point_3d is None:
        self.gaze_point_3d = geometry_msgs.msg.Point()
      if self.norm_pos is None:
        self.norm_pos = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.gaze_point_3d.x, _x.gaze_point_3d.y, _x.gaze_point_3d.z, _x.norm_pos.x, _x.norm_pos.y, _x.norm_pos.z, _x.calib_rotation, _x.label,) = _get_struct_7dI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7dI = None
def _get_struct_7dI():
    global _struct_7dI
    if _struct_7dI is None:
        _struct_7dI = struct.Struct("<7dI")
    return _struct_7dI
