(cl:in-package kaaican-msg)
(cl:export '(TOSEC-VAL
          TOSEC
          TIME-VAL
          TIME
          COUNT-VAL
          COUNT
          ID-VAL
          ID
          LEN-VAL
          LEN
          DATA-VAL
          DATA
          STATUS-VAL
          STATUS
          AA-VAL
          AA
          BB-VAL
          BB
          CC-VAL
          CC
          DD-VAL
          DD
          EE-VAL
          EE
          FF-VAL
          FF
          GG-VAL
          GG
          HH-VAL
          HH
          II-VAL
          II
          JJ-VAL
          JJ
          KK-VAL
          KK
          LL-VAL
          LL
          MM-VAL
          MM
          NN-VAL
          NN
          OO-VAL
          OO
          HEADER-VAL
          HEADER
))