(cl:in-package kaaican-msg)
(cl:export '(MOBILEYE_CAN_MESSAGE_TEST_NUMBER-VAL
          MOBILEYE_CAN_MESSAGE_TEST_NUMBER
          MSG_COUNT-VAL
          MSG_COUNT
          MSG_STATUS-VAL
          MSG_STATUS
          TOSEC-VAL
          TOSEC
          DISTANCE_LEFT_LANE-VAL
          DISTANCE_LEFT_LANE
          DISTANCE_RIGHT_LANE-VAL
          DISTANCE_RIGHT_LANE
          O_ID-VAL
          O_ID
          O_POSITION_X-VAL
          O_POSITION_X
          O_POSITION_Y-VAL
          O_POSITION_Y
          O_RELATIVE_VELOCITY_X-VAL
          O_RELATIVE_VELOCITY_X
          O_BRAKE_LIGHT-VAL
          O_BRAKE_LIGHT
          O_TYPE-VAL
          O_TYPE
          O_STATUS-VAL
          O_STATUS
          O_CHANGE-VAL
          O_CHANGE
))