(cl:in-package kaaican-msg)
(cl:export '(MSG_PUB_CNT-VAL
          MSG_PUB_CNT
          MSG_SUB_CNT-VAL
          MSG_SUB_CNT
          STEERING_ANGLE_FEEDBACK-VAL
          STEERING_ANGLE_FEEDBACK
          APS_ANALOG_FEEDBACK-VAL
          APS_ANALOG_FEEDBACK
          TAIL_LAMP-VAL
          TAIL_LAMP
          WIPER-VAL
          WIPER
          TRUN_LAMP-VAL
          TRUN_LAMP
          MODE-VAL
          MODE
          MODE_FEEDBACK-VAL
          MODE_FEEDBACK
          ERROR_STATUS-VAL
          ERROR_STATUS
          DESIRED_STEERING_ANGLE-VAL
          DESIRED_STEERING_ANGLE
          STATUS-VAL
          STATUS
          RESERVED-VAL
          RESERVED
          TM_G_SEL_DISP-VAL
          TM_G_SEL_DISP
          ACCEL-VAL
          ACCEL
          MODE_FEEDBACK-VAL
          MODE_FEEDBACK
          ASM_STATE-VAL
          ASM_STATE
          ERROR_STATUS-VAL
          ERROR_STATUS
          BRAKE_ACTUTATOR_POSITION-VAL
          BRAKE_ACTUTATOR_POSITION
          ANGLE-VAL
          ANGLE
          BRAKE_PEDAL-VAL
          BRAKE_PEDAL
))