(cl:in-package kaaican-msg)
(cl:export '(MOBILEYE_CAN_MESSAGE_NUMBER-VAL
          MOBILEYE_CAN_MESSAGE_NUMBER
          MSG_COUNT-VAL
          MSG_COUNT
          MSG_STATUS-VAL
          MSG_STATUS
          TOSEC-VAL
          TOSEC
          TIME-VAL
          TIME
          CON_LEFT-VAL
          CON_LEFT
          LDW_LEFT-VAL
          LDW_LEFT
          TYPE_LEFT-VAL
          TYPE_LEFT
          DIS_LEFT-VAL
          DIS_LEFT
          CON_RIGHT-VAL
          CON_RIGHT
          LDW_RIGHT-VAL
          LDW_RIGHT
          TYPE_RIGHT-VAL
          TYPE_RIGHT
          DIS_RIGHT-VAL
          DIS_RIGHT
          HEAD_VALID-VAL
          HEAD_VALID
          HEAD_MEA-VAL
          HEAD_MEA
          LDW_OFF-VAL
          LDW_OFF
          LDW_LEFT_ON-VAL
          LDW_LEFT_ON
          LDW_RIGHT_ON-VAL
          LDW_RIGHT_ON
          FCW_ON-VAL
          FCW_ON
          LEFT_CROSSING_EVENT-VAL
          LEFT_CROSSING_EVENT
          RIGHT_CROSSING_EVENT-VAL
          RIGHT_CROSSING_EVENT
          P_FCW-VAL
          P_FCW
          P_DZ-VAL
          P_DZ
          TSR_EN-VAL
          TSR_EN
          TSR_W_LV-VAL
          TSR_W_LV
          HEAD_W_LV-VAL
          HEAD_W_LV
          HW_R_EN-VAL
          HW_R_EN
          SIGN1-VAL
          SIGN1
          SIGN2-VAL
          SIGN2
          SIGN3-VAL
          SIGN3
          SIGN4-VAL
          SIGN4
          S_SIGN1-VAL
          S_SIGN1
          S_SIGN2-VAL
          S_SIGN2
          S_SIGN3-VAL
          S_SIGN3
          S_SIGN4-VAL
          S_SIGN4
          HLB_DEC-VAL
          HLB_DEC
          L_BEAM-VAL
          L_BEAM
          L_CUR-VAL
          L_CUR
          L_HEAD-VAL
          L_HEAD
          CON_AREA-VAL
          CON_AREA
          R_LDW-VAL
          R_LDW
          L_LDW-VAL
          L_LDW
          YAW-VAL
          YAW
          PITCH-VAL
          PITCH
          NUM_O-VAL
          NUM_O
          TIMESTAMP-VAL
          TIMESTAMP
          L_CLOSE-VAL
          L_CLOSE
          R_CLOSE-VAL
          R_CLOSE
          GO-VAL
          GO
          CLOSE_CAR-VAL
          CLOSE_CAR
          L_SIGNAL-VAL
          L_SIGNAL
          R_SIGNAL-VAL
          R_SIGNAL
          WIPER-VAL
          WIPER
          LO_BEAM-VAL
          LO_BEAM
          HI_BEAM-VAL
          HI_BEAM
          SPEED-VAL
          SPEED
          SIGN_TYPE-VAL
          SIGN_TYPE
          S_SIGN_TYPE-VAL
          S_SIGN_TYPE
          SIGN_X-VAL
          SIGN_X
          SIGN_Y-VAL
          SIGN_Y
          SIGN_Z-VAL
          SIGN_Z
          FILTER_TYPE-VAL
          FILTER_TYPE
))