(cl:in-package kaaican-msg)
(cl:export '(UDS_COUNT-VAL
          UDS_COUNT
          GAP-VAL
          GAP
          OBD_RPM-VAL
          OBD_RPM
          OBD_SPEED-VAL
          OBD_SPEED
          VEHICLE_SPEED_1-VAL
          VEHICLE_SPEED_1
          VEHICLE_SPEED_2-VAL
          VEHICLE_SPEED_2
          ACCLEARTOR_POSITION-VAL
          ACCLEARTOR_POSITION
          DRIVER_SETTING_TARGET_SPEED-VAL
          DRIVER_SETTING_TARGET_SPEED
          DISTANCE_TO_TARGET-VAL
          DISTANCE_TO_TARGET
          RELATIVE_SPEED_TO_TARGET-VAL
          RELATIVE_SPEED_TO_TARGET
          ABSOLUTE_STEERING_ANGLE-VAL
          ABSOLUTE_STEERING_ANGLE
          STEERING_WHEEL_ANGLE_SENSOR-VAL
          STEERING_WHEEL_ANGLE_SENSOR
))